### ISSUE TITLE
Clicking outside of modal does not resolve/reject

### ISSUE THREAD

**Issue by robertcoltheart** [Arexo/ember-cli-modal-service#1]
I noticed that clicking outside of the modal closes it, but neither the resolve or reject functions are called. Possible bug?

**Comment by fiftoine** [comment]
This feature is not handled... yet? 
Isn't it a third way of closing a modal? Resolve when pushed on save btn, reject when pushed on cancel button. What should it call when clicking outside the modal? Configurable?

Thanks for your remark

**Comment by serega104** [comment]
I think it needs to behave Identical to clicking X button, which would be rejected with no value.
Also, esc should do the same.

**Comment by robertcoltheart** [comment]
Agreed. I think this should be the ideal behaviour.

**Comment by fiftoine** [comment]
Sorry for the late reaction y'all. I'll implement it very soon...
